# =========================================
# Alacritty Theme: Manjaro Dark Green 🌿
# =========================================

[colors.primary]
background = "#1E1E1E"
foreground = "#D0D0D0"

[colors.normal]
black   = "#2D2D2D"
red     = "#E06C75"
green   = "#34BE5B"
yellow  = "#E5C07B"
blue    = "#61AFEF"
magenta = "#C678DD"
cyan    = "#56B6C2"
white   = "#ABB2BF"

[colors.bright]
black   = "#5C6370"
red     = "#FF7A86"
green   = "#41DF7C"
yellow  = "#FFD97B"
blue    = "#78A9FF"
magenta = "#DA70D6"
cyan    = "#89DDFF"
white   = "#FFFFFF"

[cursor]
style = "Beam"
unfocused_hollow = true

[window]
opacity = 0.93
dynamic_padding = true
padding = { x = 8, y = 6 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0

